server:
  host: "localhost"
  port: ":8000"
db:
  username: "postgres"
  host: "0.0.0.0"
  port: "5432"
  dbname: "dbL0"
  password: "pusinu48"
  sslmode: "disable"
nats-streaming:
  clusterID: "test-cluster"
  clientID: "test-client"
  chanel: "foo"
